config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  

   root 'events#index'

    get ':id/attend' => 'events#attend', as: :event_attend
    get ':id/unattend' => 'events#unattend', as: :event_unattend
    resources :events

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :bookings
  has_many :users, through: :bookings 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookings
  has_many :events, through: :bookings        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    if user_signed_in?
      @events = Event.all
      
    else 
      flash[:notice] = "Please login first"
      redirect_to new_user_session_path
    end  
  end
  def create
    @event = Event.create(event_params)
    flash[:notice] = "Event created."
    redirect_to root_path
  end
  def new
    if current_user.email == "admin@admin.com"
      @event = Event.new
    else
      flash[:notice] = "Not authorized to access."
      redirect_to root_path
    end  
  end
  def edit
  end
  def show
    @event = Event.find(params[:id])
    @user = @event.users.find_by(email: current_user.email)

  end
  def update
  end
  def destroy
  end
  def attend
   @event = Event.find_by(id: params[:id]) 
   @user = User.find_by(email: current_user.email)
   @event.users << @user
   redirect_to event_path(@event)
  end
  def unattend
   @event = Event.find_by(id: params[:id]) 
   @user = User.find_by(email: current_user.email)
   @event.users.delete(@user)
   redirect_to event_path 
  end
  
  private
  def event_params
    params.require(:event).permit(:event_name, :event_type, :event_date, :event_location, :event_description)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/index.html.erb
<h1><center> Event List </center></h1>
<!-- Function for getting month-->
<% def get_month(res) %>
    <% s = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"] %>
    <% return s[(res.to_i)-1] %>
<% end %>
<!-- Function for getting month-->

<% @events.each do|e| %>
  <% @event_date = e.event_date %>
  <% @edate = @event_date.to_s %>
  <div class = "container-fluid">
    <div class = "row ">
      <div id= "coloumn-height">
        <div class = "col-lg-10 col-lg-offset-2">
          <div class = "demo grid-margin col-lg-2 ">   
            <div class = "date-cell-item">
              <h1> <%= @edate[8..9] %></h1>
              <h2> <%= get_month(@edate[5..6]) %></h2><br>
              <h4> <span class = "glyphicon glyphicon-map-marker" aria-hidden = "true"></span> <%= e.event_location %> </h4>
            </div>
          </div>
          <div class = "grid-margin col-lg-4 demo">
            <div class = "cell-item">
              <h4><i> Event Name: <%= e.event_name %></i></h4><br>
              <h4><i> Event Type: <%= e.event_type %></i></h4></h4><br>
              <blockquote> <%= e.event_description %></blockquote><br>
              <% if Time.now > @event_date %>
                <%= link_to 'Registrations Closed', event_path(e), class: "btn btn-danger" %><br><br>
              <% else %>
                <%= link_to 'Registrations Open', event_path(e), class: "btn btn-success" %><br><br>
              <% end %>
            </div>
          </div>
          <div class = "grid-margin col-lg-3 demo">
            <div class = "cell-item">
              <h2><i> Pricing coloumn </i></h2>
              <h4> Ticket Price: <span class = "glyphicon glyphicon-euro" aria-hidden = "true"></span> </h4><br>
            </div>
          </div>
        </div> 
      </div>
    </div>  
  </div>  
<% end %>

app/views/events/new.html.erb
<h1> Form For new Event </h1>
<%= form_for @event, url: events_path do|f| %>
  <div class="field form-group">
    <%= f.label :event_name, class: 'col-lg-offset-3 col-lg-4 control-label'%>
    <div class=" col-lg-offset-3 col-lg-5">
      <%= f.text_field :event_name, class: ' form-control' %>
    </div>
  <br><br><br><br>
  </div>
  <div class="field form-group">
    <%= f.label :event_type, class: 'col-lg-offset-3 col-lg-3 control-label' %>
    <div class="col-lg-offset-3 col-lg-5">
      <%= f.text_field :event_type,class: 'form-control' %> <br>
    </div>
  </div>
  <br><br><br><br>
  </div>
  <div class="field form-group">
    <%= f.label :event_date, class: 'col-lg-offset-3 col-lg-3 control-label' %>
    <div class="col-lg-offset-3 col-lg-5">
      <%= f.text_field :event_date,class: 'form-control' %> <br>
    </div>
  </div>
  <br><br><br><br>
  </div>
  <div class="field form-group">
    <%= f.label :event_location, class: 'col-lg-offset-3 col-lg-3 control-label' %>
    <div class="col-lg-offset-3 col-lg-5">
      <%= f.text_field :event_location,class: 'form-control' %> <br>
    </div>
  </div>
  <br><br><br><br>
  </div>
  <div class="field form-group">
    <%= f.label :event_description, class: 'col-lg-offset-3 col-lg-3 control-label' %>
    <div class="col-lg-offset-3 col-lg-5">
      <%= f.text_field :event_description,class: 'form-control' %> <br>
    </div>
  </div>
  <br><br><br><br>
  <div class="actions form-group">
    <div class="col-lg-offset-3 col-lg-2">
      <%= f.submit %>
    </div>
  </div>
  
<%end%>

app/views/events/show.html.erb
<div class = "container-fluid">
  <div class = "row">
    <div class = "col-lg-6 col-lg-offset-1">
      <div class = "event-show-items">
        <% if @user.present? && Time.now < @event.event_date %> 
          <h1><b> Event Page </b> <span class = "attending-success"> (You have already registered this event) </span></h1>
        <% end %>
        <% if !@user.present? && Time.now < @event.event_date %>
          <h1><b> Event Page </b> <span class = "attending-a"> (You are eligible to register for this event) </span></h1>  
        <% end %>
        <% if Time.now > @event.event_date %>
          <h1><b> Event Page </b>  (Past Event.) </h1>  
        <% end %>
        <i><h3> Name: <%= @event.event_name %></h3>
        <h3> Type: <%= @event.event_type %></h3>
        <h3> Date: <%= @event.event_date %></h3>
        <h3> Location: <%= @event.event_location %></h3>
        <h3> Description: <%= @event.event_description %></h3></i>
        <% if Time.now > @event.event_date %>

          <%= link_to 'Attend Event', event_attend_path(@event),class: "btn btn-success disabled" %>
          <%= link_to 'Unattend Event', event_unattend_path(@event),class: "btn btn-danger disabled" %>  
        <% elsif @user.present? %>
          
          <%= link_to 'Attend Event', event_attend_path(@event),class: "btn btn-success disabled" %>
          <%= link_to 'Unattend Event', event_unattend_path(@event),class: "btn btn-danger" %>  
          
        <% else %>
          <%= link_to 'Attend Event', event_attend_path(@event),class: "btn btn-success " %>
          <%= link_to 'Unattend Event', event_unattend_path(@event),class: "btn btn-danger disabled" %>  
        <% end %>
      </div>
    </div>
    <div class = "col-lg-3 col-lg-offset-1">
      <div class = "event-show-items">
      <h1> People who are Attending </h1>
      <% @event.users.each do|u| %>
         <h4> <%= u.email %> </h4>
      <% end %>
      </div>
    </div>      
  </div>  
</div>

app/views/home/index.html.erb
<h1> This is welcome index </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ticketadmin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>

<!-- Navbar starts here  --> 
<nav class="nav-theme navbar navbar-custom navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Ticket Admin <span class="glyphicon glyphicon-registration-mark" aria-hidden="true"></span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %><span class="sr-only">(current)</span></li> <!-- Link to home page-->
        <% if user_signed_in? && current_user.email == "admin@admin.com" %>
          <li><%= link_to 'Add Event', new_event_path %><span class="sr-only">(current)</span></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
          <li><%= link_to 'Register', new_user_registration_path %><span class="sr-only">(current)</span></li> <!-- Link to Register page-->
          <li><%= link_to 'Login', new_user_session_path %><span class="sr-only">(current)</span></li> <!-- Link to login page-->
        <% else %>
          <li class="nav-text"><span class="font-theme"> Signed in as <%= current_user.email %> </span><span class="sr-only">(current) </span></li>
          <li><%= link_to 'Logout', destroy_user_session_path,method: :delete %><span class="sr-only">(current)</span></li> <!-- Link to logout page-->
        <% end %>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- Navbar Ends here -->
<% if flash[:notice] %>
  <div class = "alert alert-success"><%= flash[:notice] %></div>
  <% end %>
<%= yield %>

</body>
</html>